[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio = { version = "1.43", features = ["full", "macros"] }
rusqlite = "0.32.1"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.135"
lazy_static = "1.4"
hex = "0.4.3"
