[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = ["full", "macros"] }
rusqlite = "0.32.1"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0.135"
